### ISSUE TITLE
what does the train data look like?

### ISSUE THREAD

**Issue by zhouzebiao** [AdinAck/Voice2Voice#1]
in this project , i cant see what the data looks like . can you offer some data ?

**Comment by AdinAck** [comment]
The training data we used was an audio clip of the target voice and input voice saying the same words at the same time with the same inflection in an attempt to make the ai only have to perform a "simple" transformation. This was for a school project and really did not work very well for a multitude of reasons, all of which we do not plan to fix. I recommend trying other voice-to-voice projects that are intended for actual functionality.
